name: Despliegue en GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Iniciar sesión en Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
      
    - name: Configurar el entorno de Google Cloud
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Compilar la aplicación
      run: mvn clean package -DskipTests

    - name: Construir la imagen de Docker
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/suggest-city .

    - name: Autenticar con el registro de contenedores de Google Cloud
      run: gcloud auth configure-docker

    - name: Subir la imagen a Google Container Registry
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/suggest-city

    - name: Desplegar en Google Cloud Run
      run: |
        gcloud run deploy api-suggest-city \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/suggest-city \
          --platform managed \
          --allow-unauthenticated

